# Generated by Django 5.2.3 on 2025-06-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_food_creator_foodlog_rename_meal_templatemeal_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemplateMealFood',
            new_name='TemplateFood',
        ),
        migrations.AlterField(
            model_name='food',
            name='calories_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
