# Generated by Django 5.2.3 on 2025-06-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_templatemealfood_templatefood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatefood',
            name='default_quantity',
        ),
    ]
