# Generated by Django 5.2.3 on 2025-07-01 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_templatefood_default_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.templatemeal'),
        ),
    ]
