# Generated by Django 5.2.3 on 2025-09-12 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_foodlog_meal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_log', to='api.food'),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_log', to='api.templatemeal'),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='templatefood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_food', to='api.food'),
        ),
        migrations.AlterField(
            model_name='templatefood',
            name='template_meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_food', to='api.templatemeal'),
        ),
        migrations.AlterField(
            model_name='templatemeal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_meal', to=settings.AUTH_USER_MODEL),
        ),
    ]
